### ISSUE TITLE
Attach files to a child page

### ISSUE THREAD

**Issue by martijnzomer** [jchristopher/attachments#136]
I'm using this plugin for years now and every time it works like charm!
However, I'm developing a website right now where I want to use this plugin on child pages.
I can see the box where I can attach my media, but when I publish my page, al my attachments are gone.
Is this a know issue or am I doing something wrong?

**Comment by ensemblebd** [comment]
same problem. Followed the faq. I'll update if I find more info.

**Comment by ensemblebd** [comment]
class.attachments.php 
line # 1652
::get_attachments_metadata()

Looks like it's returning a valid json decoded object from metadata. However it doesn't contain a member named "$instance", therefore the if() block doesn't process the attachments, period.  It's a simple array of metadata attachments, so am not sure how it's supposed to work anyway. The "$instance" variable is never assigned.
That's why there is nothing on the page.

Will investigate more if time permits... Is the author active on this forum or no?

**Comment by ensemblebd** [comment]
figured it out. $instance is a variable passed in as first argument to constructor.
So it's operating properly. The problem is that the documentation tells you to use:
`<?php $attachments = new Attachments( 'attachments',$post->ID ); /* pass the instance name */ ?>`

and the code sample provided uses the definition in functions.php of **"my_attachments". NOT "attachments".**

Simply change it to use the correct "$instance" name, to match your definition within functions.php. And it works fine.

**Comment by fvdm** [comment]
I have struggled with this too and still can't get Attachments UI to auto-append the instances. For lack of time to track down the problem I now use the Header/Footer plugin to add custom PHP at the end of all posts.

This code is based on the example displayed on the instance edit screen and works fine for me. Maybe it's useful to you. Btw, I don't have to include the `$post->ID`.

```php
// generic attachments (without UI instance)
$att = new Attachments('attachments');
if ($att->exist()) {
  while ($att->get()) {
    // downloads html
  }
}

// and for special attachments (UI instance 'aerials')
$aerials = new Attachments('attachments_aerials');
if ($aerials->exist()) {
  while ($aerials->get()) {
    // image grid html
    // $att->
  }
}
```

**Comment by jchristopher** [comment]
Hello, given the age of this Issue I'm going to mark it as Closed but if this is still a problem please comment here!
