### ISSUE TITLE
Shuffle Attachments

### ISSUE THREAD

**Issue by vanthuanqs** [jchristopher/attachments#160]
It will be good if the plugin have a function to shuffle attachments before get them in while loop.
Example:

```
<?php
$attachments = new Attachments( 'attachments', 123 );
$attachments->shuffle();
?>
<?php if( $attachments->exist() ) : ?>
    <h3>Attachments</h3>
    <ul>
        <?php while( $attachment = $attachments->get() ) : ?>
            <li>
                <pre><?php print_r( $attachment ); ?></pre>
            </li>
        <?php endwhile; ?>
    </ul>
<?php endif; ?>
```

At my own work, I edit and add this function to `Main Attachments Class`

```
/**
* Shuffle attachments
*
* @return null
*/
public function shuffle() {
    shuffle($this->attachments);
}
```

**Comment by orionrush** [comment]
I like this, and will probably implement it myself. Two thoughts:

1. Offer a [Pull Request](https://help.github.com/articles/creating-a-pull-request/) and make it easy for Jonathan to review it and add it to the plugin. 

1.  Rather than modify the plugin code directly, [extend the class](http://php.net/manual/en/keyword.extends.php) to add your own method (funtion). This could be done in your own helper plugin that loads after the attachments plugin, or in your theme's functions.php. This way if there is an Attachments update, your custom modification isn't overwritten.

**Comment by jchristopher** [comment]
Hi there yes please see [these docs](https://github.com/jchristopher/attachments/blob/3.5.6/docs/hooks.md#get-attachments)
