### ISSUE TITLE
Disable Settings Screen - documentation mix up

### ISSUE THREAD

**Issue by valivvvv** [jchristopher/attachments#162]
Check up your documentation here: https://github.com/jchristopher/attachments/blob/master/docs/usage.md#disable-settings-screen

`add_filter( 'attachments_settings_screen', '__return_false' ); // disable the Settings screen`

This should be added to functions.php, not wp-config.php, as currently stated.

Great plugin, cheers!

**Comment by orionrush** [comment]
Of course that means that all someone has to do to enable the settings is change the theme . . . .

**Comment by tcoukoulis** [comment]
I ran into this issue, too.

![image](https://cloud.githubusercontent.com/assets/2925009/18500364/73ba7e26-7a0c-11e6-9a0e-fb1193da49a2.png)

Resulted in:

    Fatal error: Call to undefined function add_filter()

When placing the code snippet from the documentation inside my theme's `functions.php` file everything worked as described.

While I understand the ramifications of coupling this setting to my theme, as @orionrush mentioned, the documentation here is resulting in fatal errors.

**Comment by tcoukoulis** [comment]
Upon further [investigation](https://github.com/jchristopher/attachments/blob/master/classes/class.attachments.php#L1826), it appears the correct documentation should instruct the developer to add,
    
    define( 'ATTACHMENTS_SETTINGS_SCREEN', false );
_before_
    
    require_once(ABSPATH . 'wp-settings.php');
inside `wp_config.php`, which makes sense since the documentation asks the developer to use the `add_filter` method which isn't defined until WordPress loads the `plugin.php` file inside `wp-settings.php`.

I tested this between multiple themes and it appears to resolve the issue.

**Comment by jameswlane** [comment]
This issue can be closed.
